M48
; DRILL file {KiCad (7.0.0)} date Thu Mar  9 18:05:23 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-09T18:05:23+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X106.935Y-88.3
X106.935Y-114.3
X126.745Y-88.3
X126.745Y-114.3
T0
M30
